-- V1__init.sql — the first Flyway migration (NS-1).
--
-- Flyway convention: V<version>__<description>.sql. Flyway applies these in
-- order and records each one in the flyway_schema_history table, so the schema
-- of ANY environment (your laptop, CI, prod) is just "V1..Vn applied in order".
-- Rule: once a migration has run anywhere shared, never edit it — add V2.
--
-- Design notes:
--  * BIGINT GENERATED BY DEFAULT AS IDENTITY = modern Postgres auto-increment,
--    pairs with JPA's GenerationType.IDENTITY.
--  * TIMESTAMPTZ (timestamp with time zone) everywhere: it stores an absolute
--    instant (UTC internally), so server timezone can never corrupt ordering —
--    and ordering is literally what a queue IS.
--  * Status columns are VARCHAR holding enum names (WAITING, SERVED, ...):
--    readable in psql, no fragile ordinal numbers.

CREATE TABLE businesses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL
);

-- An owner is the human account that logs in; it belongs to exactly one
-- business (this is a 1-owner-per-business MVP, but the FK already allows
-- multiple owners/staff accounts per business later).
CREATE TABLE owners (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT       NOT NULL REFERENCES businesses (id),
    email         VARCHAR(255) NOT NULL UNIQUE,          -- login identifier; UNIQUE enforced by the DB, not just app code
    password_hash VARCHAR(100) NOT NULL,                 -- BCrypt output (~60 chars); NEVER the plaintext password
    display_name  VARCHAR(100) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE queues (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id             BIGINT       NOT NULL REFERENCES businesses (id),
    name                    VARCHAR(255) NOT NULL,
    join_token              VARCHAR(36)  NOT NULL UNIQUE, -- random UUID in the shareable link; unguessable, unlike the numeric id
    status                  VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    station_count           INT          NOT NULL DEFAULT 1,  -- how many chairs/counters serve in parallel (used by the wait estimate)
    default_service_minutes INT          NOT NULL DEFAULT 15, -- owner's guess at minutes-per-customer (real medians arrive in Sprint 5)
    created_at              TIMESTAMPTZ  NOT NULL
);

CREATE TABLE queue_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id      BIGINT       NOT NULL REFERENCES queues (id),
    customer_name VARCHAR(100) NOT NULL,
    party_size    INT          NOT NULL DEFAULT 1,
    status        VARCHAR(20)  NOT NULL DEFAULT 'WAITING',
    entry_token   VARCHAR(36)  NOT NULL UNIQUE, -- the customer's private handle on their ticket (they have no account)
    joined_at     TIMESTAMPTZ  NOT NULL,        -- position = order of joined_at among WAITING entries
    called_at     TIMESTAMPTZ,                  -- unused until "you're up" notifications (Sprint 2)
    served_at     TIMESTAMPTZ
);

-- Indexes for the queries we actually run:
CREATE INDEX idx_owners_business        ON owners (business_id);
CREATE INDEX idx_queues_business        ON queues (business_id);
-- The hot path: "WAITING entries of queue X, ordered by join time" — used by
-- position computation, the staff list, and advance-the-line.
CREATE INDEX idx_entries_queue_status_joined ON queue_entries (queue_id, status, joined_at);
