-- V3 — Sprint 3: measured wait estimates + "you're up" notifications.

-- FR: wait estimate from REAL data instead of the owner's guess (PRD §3.8.2).
-- One row per customer served. We keep raw samples rather than a running
-- average because a median needs the actual values, and because raw data can
-- be re-analysed later (Sprint 5 wants percentiles) while an average cannot.
CREATE TABLE service_samples (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id         BIGINT      NOT NULL REFERENCES queues (id),
    duration_seconds INT         NOT NULL,
    completed_at     TIMESTAMPTZ NOT NULL
);
-- The only query we run: "the N most recent samples for this queue".
CREATE INDEX idx_service_samples_queue_recent ON service_samples (queue_id, completed_at DESC);

-- How we measure a "service duration" without a start button:
-- the gap between two consecutive advances. That interval already accounts
-- for parallel stations (2 chairs = advances twice as often), so the estimate
-- does NOT divide by station_count the way the old guess did.
ALTER TABLE queues ADD COLUMN last_advance_at TIMESTAMPTZ;

-- FR-8. Set the first time we tell this customer "you're next", so a
-- reconnect, a second staff action, or a redelivered event can't buzz the
-- same phone over and over. Making the send IDEMPOTENT (safe to attempt more
-- than once) is what lets the rest of the system be at-least-once.
ALTER TABLE queue_entries ADD COLUMN next_notified_at TIMESTAMPTZ;

-- FR-8. One row per device that agreed to receive notifications for a ticket.
-- endpoint is a URL at the browser vendor's push service (Google/Mozilla/
-- Apple) — we never talk to the phone directly. p256dh + auth are the keys
-- that let us ENCRYPT the payload so the push service can relay it without
-- being able to read it.
CREATE TABLE push_subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id   BIGINT       NOT NULL REFERENCES queue_entries (id),
    endpoint   TEXT         NOT NULL,   -- can be long; TEXT not VARCHAR
    p256dh     VARCHAR(255) NOT NULL,
    auth       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    -- One device subscribes once per ticket. Re-subscribing (a page reload)
    -- must not pile up duplicate rows and send four identical buzzes.
    CONSTRAINT uq_push_entry_endpoint UNIQUE (entry_id, endpoint)
);
CREATE INDEX idx_push_subscriptions_entry ON push_subscriptions (entry_id);
