-- V4 — Sprint 4: advance reservations (FR-10).

-- Booking configuration lives on the QUEUE, because a queue is the thing a
-- customer joins — walk-in or booked.
ALTER TABLE queues ADD COLUMN reservations_enabled BOOLEAN     NOT NULL DEFAULT false;
ALTER TABLE queues ADD COLUMN opening_time         TIME;                       -- local wall-clock, e.g. 09:00
ALTER TABLE queues ADD COLUMN closing_time         TIME;                       -- e.g. 17:00
ALTER TABLE queues ADD COLUMN slot_minutes         INT         NOT NULL DEFAULT 30;
ALTER TABLE queues ADD COLUMN slot_capacity        INT         NOT NULL DEFAULT 1;
-- The business's zone. Opening hours are wall-clock facts ("we open at 9"),
-- so they need a zone to become real instants — and that conversion must
-- respect daylight saving, which is why we store an IANA id and not an offset.
ALTER TABLE queues ADD COLUMN time_zone            VARCHAR(64) NOT NULL DEFAULT 'UTC';

-- DESIGN NOTE — a deliberate deviation from PRD §3.3, which sketches a
-- `slots` table with a capacity column.
--
-- We do NOT materialise slot rows. Slot times are derived from the config
-- above for whatever date is asked about, so there is no nightly job creating
-- rows that mostly go unused, and changing opening hours takes effect
-- immediately instead of needing a backfill.
--
-- Capacity is then enforced by SEAT NUMBER plus a UNIQUE constraint rather
-- than by counting rows. Counting is what creates the classic double-booking
-- race: two customers both COUNT 0 free seats before either INSERTs. Here,
-- two concurrent bookings for the same seat collide on the constraint, the
-- database picks exactly one winner, and the loser simply retries the next
-- seat. The rule lives below all application code, so a future endpoint that
-- forgets to check still cannot overbook.
CREATE TABLE reservations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id          BIGINT       NOT NULL REFERENCES queues (id),
    slot_start        TIMESTAMPTZ  NOT NULL,
    seat_no           INT          NOT NULL,          -- 0 .. slot_capacity-1
    customer_name     VARCHAR(100) NOT NULL,
    contact           VARCHAR(255),
    party_size        INT          NOT NULL DEFAULT 1,
    status            VARCHAR(20)  NOT NULL DEFAULT 'BOOKED',
    reservation_token VARCHAR(36)  NOT NULL UNIQUE,   -- the customer's private handle
    idempotency_key   VARCHAR(100),
    created_at        TIMESTAMPTZ  NOT NULL
);

-- A PARTIAL unique index, not a plain UNIQUE constraint. The difference
-- matters: a cancelled booking must RELEASE its seat so someone else can take
-- it, but we still want to keep the row for history. Excluding CANCELLED from
-- the index gives us both. (A plain constraint would keep the seat locked
-- forever by a booking nobody is coming to.)
CREATE UNIQUE INDEX uq_reservation_seat
    ON reservations (queue_id, slot_start, seat_no)
    WHERE status <> 'CANCELLED';

CREATE INDEX idx_reservations_queue_slot ON reservations (queue_id, slot_start);

-- IDEMPOTENCY (Sprint 4's headline safety feature). A customer on a flaky
-- connection taps "Book", the request succeeds, the response is lost, they
-- tap again. Without this they hold two reservations. The client sends a
-- unique key per booking ATTEMPT; a repeat with the same key returns the
-- original booking instead of making a second one.
-- Partial index: only rows that actually carry a key are constrained.
CREATE UNIQUE INDEX uq_reservation_idempotency
    ON reservations (queue_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- THE SHARED ABSTRACTION (PRD §3.2). A walk-in and a reservation are
-- different front doors to one idea: "when is this person due?". Everything
-- downstream — notifications, displays, and Sprint 5's leave-by maths — reads
-- this single field and never asks which door someone came through.
ALTER TABLE queue_entries ADD COLUMN target_serve_time TIMESTAMPTZ;
-- Set when a reservation is redeemed into the line, so the entry knows where
-- it came from (and so we don't redeem the same booking twice).
ALTER TABLE queue_entries ADD COLUMN reservation_id BIGINT REFERENCES reservations (id);
CREATE UNIQUE INDEX uq_queue_entries_reservation
    ON queue_entries (reservation_id) WHERE reservation_id IS NOT NULL;
