-- V5 — Sprint 5: the "Leave Now" engine (FR-11 … FR-17).

-- The DESTINATION. Everything in this sprint answers "how long to get from
-- where you are to here?", which needs a "here".
ALTER TABLE queues ADD COLUMN venue_latitude  DOUBLE PRECISION;
ALTER TABLE queues ADD COLUMN venue_longitude DOUBLE PRECISION;

-- Business-configured policy (FR-16). When someone's turn arrives before they
-- do, what happens? Hold the spot for grace_minutes, then either push them
-- back bump_places positions or mark them a no-show (bump_places = 0).
ALTER TABLE queues ADD COLUMN grace_minutes          INT NOT NULL DEFAULT 5;
ALTER TABLE queues ADD COLUMN bump_places            INT NOT NULL DEFAULT 2;
-- Padding on every leave-by time. Cheap insurance against being slightly wrong
-- in the direction that costs someone their turn.
ALTER TABLE queues ADD COLUMN safety_buffer_minutes  INT NOT NULL DEFAULT 5;

-- FR-11. An AUDIT of consent — deliberately WITHOUT coordinates (PRD §3.8.8).
-- Where somebody physically is belongs in Redis with a TTL, so it expires by
-- itself and never lands in a backup, a replica, or an analytics export. What
-- we keep permanently is only the fact that they agreed, and when they took
-- it back — which is what you need to answer a privacy complaint.
CREATE TABLE tracking_consents (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id         BIGINT      NOT NULL REFERENCES queue_entries (id),
    consent_given_at TIMESTAMPTZ NOT NULL,
    revoked_at       TIMESTAMPTZ
);
CREATE INDEX idx_tracking_consents_entry ON tracking_consents (entry_id);

-- FR-13/FR-14. What we told them and when. This table is what stops the
-- engine from becoming a spam machine: before sending anything we ask "have I
-- already said this, and how recently?".
CREATE TABLE leave_now_alerts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id                BIGINT      NOT NULL REFERENCES queue_entries (id),
    sent_at                 TIMESTAMPTZ NOT NULL,
    alert_type              VARCHAR(20) NOT NULL,  -- LEAVE_NOW | CORRECTION
    computed_travel_minutes INT         NOT NULL
);
CREATE INDEX idx_leave_now_alerts_entry ON leave_now_alerts (entry_id, sent_at DESC);

-- FR-15: the customer confirms they're coming; staff sees it on the dashboard.
ALTER TABLE queue_entries ADD COLUMN en_route_at TIMESTAMPTZ;
-- FR-16: when the held spot stops being held.
ALTER TABLE queue_entries ADD COLUMN grace_expires_at TIMESTAMPTZ;

-- FR-16 needs to MOVE someone within the line, which forces a modelling
-- decision we'd been able to avoid until now.
--
-- Until Sprint 5, position was derived from joined_at — fine, because nobody
-- ever moved. Bumping could be implemented by rewriting joined_at, and that
-- is exactly the wrong instinct: joined_at means "when this person arrived",
-- it is a FACT, and "waited 40 minutes" is computed from it. Rewriting
-- history to change a sort order corrupts the analytics Sprint 3 just began
-- collecting. (It also silently does nothing, because the column is mapped
-- updatable = false — a bug that fails quietly rather than loudly.)
--
-- So ordering gets its own column. joined_at keeps its honest meaning;
-- queue_order_at is what the line is sorted by and the only thing a bump
-- touches. Two concepts that were coincidentally equal now have two names —
-- usually the right fix when one field is being asked to mean two things.
ALTER TABLE queue_entries ADD COLUMN queue_order_at TIMESTAMPTZ;
UPDATE queue_entries SET queue_order_at = joined_at WHERE queue_order_at IS NULL;
ALTER TABLE queue_entries ALTER COLUMN queue_order_at SET NOT NULL;

-- The hot-path index follows the new sort key.
CREATE INDEX idx_entries_queue_status_order ON queue_entries (queue_id, status, queue_order_at);
