package com.nowserving.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

/**
 * The tenant. Every queue and every owner account hangs off a Business — and
 * every query in the app is scoped by business_id (tenant isolation, NS-4).
 *
 * Entity conventions used across this project:
 *  - {@code @Getter/@Setter} but deliberately NOT Lombok's {@code @Data}:
 *    &#64;Data generates equals/hashCode over all fields, which breaks badly on
 *    JPA entities (identity should be the id, and lazy fields may not be
 *    loaded when equals is called).
 *  - A no-arg constructor is required by JPA (Hibernate instantiates entities
 *    reflectively, then populates fields).
 *  - {@code GenerationType.IDENTITY}: the DB assigns the id on INSERT — pairs
 *    with the {@code GENERATED BY DEFAULT AS IDENTITY} columns in V1__init.sql.
 */
@Entity
@Table(name = "businesses")
@Getter
@Setter
@NoArgsConstructor
public class Business {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    /**
     * The restaurant's PERMANENT public identity — what its printed QR code
     * encodes, and the only public token that outlives its queues.
     *
     * updatable = false for the same reason as Queue.joinToken: this ends up
     * on physical signage. A token that can be rotated is a token that can
     * invalidate every poster a restaurant has printed.
     */
    @Column(name = "public_token", nullable = false, unique = true, updatable = false)
    private String publicToken;

    // Hibernate's default naming strategy maps camelCase -> snake_case, so this
    // lands in the created_at column without an explicit @Column(name=...).
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** JPA lifecycle hook: runs just before the first INSERT of this row. */
    @PrePersist
    void onCreate() {
        this.createdAt = Instant.now();
        // Generated here, not by a service, so EVERY path that creates a
        // business gets a QR automatically — password signup, Google signup,
        // tests, and anything added later. There is no "create the QR" step
        // anyone can forget.
        if (this.publicToken == null) {
            this.publicToken = UUID.randomUUID().toString();
        }
    }

    public Business(String name) {
        this.name = name;
    }
}
